### ISSUE TITLE
Warn: ann error: ann:open  Make sure you have ANN class installed:

### ISSUE THREAD

**Issue by lynn2liu** [shaibagon/robustpn#1]
I ran the test_ann_class.m code in the ann_wrapper, it says done testing. But when I ran the robustpn_test code, it says "Warn: ann error: ann:open Make sure you have ANN class installed: ". Why is this happening.

**Comment by shaibagon** [comment]
@lynn2liu ANN class is in your matlab's path? see [`addpath()`](https://www.mathworks.com/help/matlab/ref/addpath.html) function for more details.

**Comment by lynn2liu** [comment]
I add both ann file and ann wraper in the path, still the same problem.

**Comment by lynn2liu** [comment]
Also, there's a warning called "searching for more points than in tree - returning only 64 ".

**Comment by shaibagon** [comment]
@lynn2liu  I never came across these issues before. I am afraid the code is too old and I no longer have access to Matlab to maintain it. 
Sorry.

**Comment by lynn2liu** [comment]
It's ok. Just to be clear, ANN class file means ann code and ann wraper code, right?

**Comment by shaibagon** [comment]
ANN is c++ code for approximate nearest neighbor search. ann_wrapper is matlab code enabling using ANN code from Matlab.
If you manage to solve this issue, can you please make a pull request with a fix? tnx!
